package com.tally.util;

public class Constants {

	public static final String DB_GET_PRODUCTS_DETAIL = "select product.productid, product.productCode , product.name , product.quantity , product.price,  supplier.supplierID , supplier.name , supplier.phone from "
														 + "products product, suppliers supplier where supplier.supplierID = product.supplierID";
	public static final String DB_ADD_PRODUCTS = "insert into products(productCode, name, quantity, price, supplierID) values (?, ?, ?, ?, ?)";
	public static final String DB_GET_SUPPLIER_DETAIL = "select supplierID, name, phone from suppliers";

	public static final String DB_ADD_TALLY_SUMMARY = "insert into tally_summary(report_id, report_name, report_key, report_value1, report_value2, created_date, check_flag) values (?, ?, ?, ?, ?, ?, ?)";
	public static final String DB_GET_TALLY_SUMMARY_REPORT_ID_NEXTVAL = "select max(report_id) report_id from tally_summary";
	public static final String DB_GET_TALLY_SUMMARY = "select tally_summary_id, report_id, report_name, report_key, report_value1, report_value2, created_date, check_flag from tally_summary where check_flag = false and report_id in (select max(report_id) from tally_summary)";
	public static final String DB_UPDATE_TALLY_SUMMARY = "update tally_summary set check_flag = true where tally_summary_id = ? and report_id = ?";
	
	public static final String DB_DELETE_DAYBOOK_MASTER = "delete from inventory.DAYBOOK_MASTER where VOUCHER_KEY = ?";
	public static final String DB_DELETE_DAYBOOK_LEDGER = "delete from inventory.DAYBOOK_INVENTORY where id > 0 and VOUCHER_KEY = ?";
	public static final String DB_DELETE_DAYBOOK_INVENTORY = "delete from inventory.DAYBOOK_LEDGER where id > 0 and VOUCHER_KEY = ?"; 
	
	//Add day book data
	public static final String DB_ADD_DAYBOOK_MASTER = "insert into DAYBOOK_MASTER(VOUCHER_KEY, VCH_TYPE, VOUCHER_DATE, VOUCHER_NUMBER, PARTY_LEDGER_NAME, EFFECTIVE_DATE, MASTER_ID, FLAG, CREATED_DATE, MODIFIED_DATE, COMPANY_ID) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
	public static final String DB_ADD_DAYBOOK_LEDGER = "insert into DAYBOOK_LEDGER(LEDGER_NAME, AMOUNT, VOUCHER_KEY, CREATED_DATE, MODIFIED_DATE, COMPANY_ID) values (?, ?, ?, ?, ?, ?)";
	public static final String DB_ADD_DAYBOOK_INVENTORY = "insert into DAYBOOK_INVENTORY(STOCK_ITEM_NAME, AMOUNT, RATE, BILLED_QTY, VOUCHER_KEY, CREATED_DATE, MODIFIED_DATE, COMPANY_ID) values (?, ?, ?, ?, ?, ?, ?, ?)";
	
	//Add stock data
	public static final String DB_ADD_STOCK = "insert into STOCK_MASTER(VOUCHER_TYPE, DATE_ENT, VOUCHER_NUMBER, VOUCHER_KEY, EFFECTIVE_DATE, MASTER_ID, OPR_DATE, REEL_WEIGHT, START_TIME, REWIND_START, REWIND_END, OPERATED_BY, FOREMAN1, FOREMAN2, CREATED_DATE, COMPANY_ID) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
	public static final String DB_ADD_STOCK_ITEM = "insert into STOCK_DETAILS(stock_details_id, STOCK_ITEM_NAME, RATE, AMOUNT, BILLED_QTY, STATUS, VOUCHER_KEY, CREATED_DATE, COMPANY_ID) values (?, ?, ?, ?, ?, ?, ?, ?, ?)";
	public static final String DB_ADD_STOCK_ITEM_DETAIL = "insert into STOCK_ITEM_DETAILS(GSM_TGT, GSM_ACT, BF_TGT, BF_ACT, COBB, REEL_LEN, JOINTS, REEL_DIA, MOIST, SIZE_ACT, SIZE_TGT, UNITS, VOUCHER_KEY, stock_details_id, CREATED_DATE, COMPANY_ID, BATCH_NAME, RATE, AMOUNT, BILLED_QTY) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
	
	public static final String DB_GET_DAYBOOK_MASTER = "select VOUCHER_KEY, VCH_TYPE, VOUCHER_ACTION, VOUCHER_DATE, VOUCHER_TYPE_NAME, VOUCHER_NUMBER, PARTY_LEDGER_NAME, EFFECTIVE_DATE, PERSISTED_VIEW, ALTER_ID, MASTER_ID, LEDGER_NAME, FLAG, CREATED_DATE, MODIFIED_DATE from DAYBOOK_MASTER where flag = false order by VOUCHER_DATE desc limit 50";
	public static final String DB_GET_DAYBOOK_LEDGER = "select ID, LEDGER_NAME, AMOUNT, VOUCHER_KEY, CREATED_DATE, MODIFIED_DATE from DAYBOOK_LEDGER";
	public static final String DB_GET_DAYBOOK_INVENTORY = "select ID, STOCK_ITEM_NAME, AMOUNT, RATE, BILLED_QTY, VOUCHER_KEY, CREATED_DATE, MODIFIED_DATE from DAYBOOK_INVENTORY";
	public static final String DB_UPDATE_DAYBOOK_INVENTORY_FLAG = "update DAYBOOK_MASTER set FLAG = 1 where VOUCHER_KEY = ?";
			
	public static final String RESPONSE_STATUS_SUCCESS = "Success";
	public static final String RESPONSE_STATUS_FAILED = "Fauliure";
	public static final String RESPONSE_MESSAGE_PRODUCT_ADD_SUCCESS = "Products added successfully";
	public static final String RESPONSE_MESSAGE_PRODUCT_ADD_FAILED = "Products are not added";
	
	public static final String REPORT_ID = "report_id";
	
	
	//tally day book master data
	public static final String TALLYMESSAGE_COUNT_EXP = "count(//ENVELOPE/BODY/DATA/TALLYMESSAGE/VOUCHER)";
	public static final String TALLYMESSAGE_COUNT_EXP_TINY = "count(//TALLYMESSAGE/VOUCHER)";
	
	public static final String ENVELOPE_BODY_DATA_TALLYMESSAGE = "//ENVELOPE/BODY/DATA/TALLYMESSAGE[";
	public static final String ENVELOPE_BODY_DATA_TALLYMESSAGE_TINY = "//TALLYMESSAGE[";
	
	public static final String VCHTYPE = "]/VOUCHER//@VCHTYPE";
	public static final String ACTION = "]/VOUCHER//@ACTION";
	public static final String DATE = "]/VOUCHER//DATE";
	public static final String VOUCHERTYPENAME = "]/VOUCHER//VOUCHERTYPENAME";
	public static final String VOUCHERNUMBER = "]/VOUCHER//VOUCHERNUMBER";
	public static final String PARTYLEDGERNAME = "]/VOUCHER//PARTYLEDGERNAME";
	public static final String VOUCHERKEY = "]/VOUCHER//VOUCHERKEY";
	public static final String EFFECTIVEDATE = "]/VOUCHER//EFFECTIVEDATE";
	public static final String PERSISTEDVIEW = "]/VOUCHER//PERSISTEDVIEW";
	public static final String ALTERID = "]/VOUCHER//ALTERID";
	public static final String MASTERID = "]/VOUCHER//MASTERID";
	
	//tally day book all ledgerlist data
	public static final String VOUCHER_ALLLEDGERENTRIES_LIST_COUNT_1 = "count(//ENVELOPE/BODY/DATA/TALLYMESSAGE[";
	public static final String VOUCHER_ALLLEDGERENTRIES_LIST_COUNT_1_TINY = "count(//TALLYMESSAGE[";
	public static final String VOUCHER_ALLLEDGERENTRIES_LIST_COUNT_2 = "]/VOUCHER//ALLLEDGERENTRIES.LIST)";
	public static final String VOUCHER_ALLLEDGERENTRIES_LIST = "]/VOUCHER//ALLLEDGERENTRIES.LIST[";
	public static final String LEDGERNAME = "]/LEDGERNAME";
	public static final String AMOUNT = "]/AMOUNT";
	public static final String ISPARTYLEDGER = "]/ISPARTYLEDGER";
	
	//tally day book ledgerlist data
	public static final String VOUCHER_LEDGERENTRIES_LIST_COUNT_1 = "count(//ENVELOPE/BODY/DATA/TALLYMESSAGE[";
	public static final String VOUCHER_LEDGERENTRIES_LIST_COUNT_1_TINY = "count(//TALLYMESSAGE[";
	public static final String VOUCHER_LEDGERENTRIES_LIST_COUNT_2 = "]/VOUCHER//LEDGERENTRIES.LIST)";
	public static final String VOUCHER_LEDGERENTRIES_LIST = "]/VOUCHER//LEDGERENTRIES.LIST[";
	
	//tally day book inventorylist data
	public static final String VOUCHER_INVENTORYENTRIES_LIST_COUNT_1 = "count(//ENVELOPE/BODY/DATA/TALLYMESSAGE[";
	public static final String VOUCHER_INVENTORYENTRIES_LIST_COUNT_1_TINY = "count(//TALLYMESSAGE[";
	public static final String VOUCHER_INVENTORYENTRIES_LIST_COUNT_2 = "]/VOUCHER//ALLINVENTORYENTRIES.LIST)";
	public static final String VOUCHER_INVENTORYENTRIES_LIST = "]/VOUCHER//ALLINVENTORYENTRIES.LIST[";
	public static final String RATE = "]/RATE";
	public static final String BILLEDQTY = "]/BILLEDQTY";
	public static final String STOCKITEMNAME = "]/STOCKITEMNAME";
	
	//tally day book inventory in list data
	public static final String VOUCHER_INVENTORYENTRIES_IN_LIST_COUNT_2 = "]/VOUCHER//INVENTORYENTRIESIN.LIST)";
	public static final String VOUCHER_INVENTORYENTRIES_IN_LIST = "]/VOUCHER//INVENTORYENTRIESIN.LIST[";
	
	public static final String LOG_BASE_FORMAT = String.format("%s={}, %s={}", "trackingid", "message");
	public static final String LOG_DATA_FORMAT = String.format("%s={}, %s={}, %s={}", "trackingid", "message", "data");
	
	//tally stock
	public static final String ALTEREDON = "]/VOUCHER//ALTEREDON";
	public static final String ACTUALQTY = "]/ACTUALQTY";
	public static final String STATUS = "]/STATUS";
	public static final String UDF_671089649 = "]/UDF_UDF_671089649.LIST//UDF_UDF_671089649";
	public static final String UDF_671089650 = "]/UDF_UDF_671089650.LIST//UDF_UDF_671089650";
	public static final String UDF_671089651 = "]/UDF_UDF_671089651.LIST//UDF_UDF_671089651";
	public static final String UDF_671089652 = "]/UDF_UDF_671089652.LIST//UDF_UDF_671089652";
	public static final String UDF_671089655 = "]/UDF_UDF_671089655.LIST//UDF_UDF_671089655";
	public static final String UDF_671089656 = "]/UDF_UDF_671089656.LIST//UDF_UDF_671089656";
	public static final String UDF_671089657 = "]/UDF_UDF_671089657.LIST//UDF_UDF_671089657";
	public static final String UDF_671089660 = "]/UDF_UDF_671089660.LIST//UDF_UDF_671089660";
	public static final String UDF_788530753 = "]/UDF_UDF_788530753.LIST//UDF_UDF_788530753";
	public static final String UDF_788538154 = "]/UDF_UDF_788538154.LIST//UDF_UDF_788538154";
	public static final String UDF_788538155 = "]/UDF_UDF_788538155.LIST//UDF_UDF_788538155";
	public static final String UDF_788538156 = "]/UDF_UDF_788538156.LIST//UDF_UDF_788538156";
	public static final String UDF_788538157 = "]/UDF_UDF_788538157.LIST//UDF_UDF_788538157";
	public static final String UDF_788538159 = "]/UDF_UDF_788538159.LIST//UDF_UDF_788538159";
	
	public static final String VOUCHER_INVENTORYENTRIESIN_LIST_COUNT_1 = "count(//ENVELOPE/BODY/DATA/TALLYMESSAGE[";
	public static final String VOUCHER_INVENTORYENTRIESIN_LIST_COUNT_2 = "]/VOUCHER//INVENTORYENTRIESIN.LIST)";
	public static final String VOUCHER_INVENTORYENTRIESIN_LIST = "]/VOUCHER//INVENTORYENTRIESIN.LIST[";
	
	public static final String INVENTORYENTRIESIN_BATCHALLOCATIONS_LIST_COUNT_1 = "count(//ENVELOPE/BODY/DATA/TALLYMESSAGE[";
	public static final String INVENTORYENTRIESIN_BATCHALLOCATIONS_LIST_COUNT_2 = "]/VOUCHER//INVENTORYENTRIESIN.LIST[";
	public static final String BATCHALLOCATIONS_LIST_COUNT_3 = "]/BATCHALLOCATIONS.LIST)";
	public static final String BATCHALLOCATIONS_LIST = "]/BATCHALLOCATIONS.LIST[";
	
	public static final String VOUCHER_INVENTORYENTRIESOUT_LIST_COUNT_1 = "count(//ENVELOPE/BODY/DATA/TALLYMESSAGE[";
	public static final String VOUCHER_INVENTORYENTRIESOUT_LIST_COUNT_2 = "]/VOUCHER//INVENTORYENTRIESOUT.LIST)";
	public static final String VOUCHER_INVENTORYENTRIESOUT_LIST = "]/VOUCHER//INVENTORYENTRIESOUT.LIST[";
	
	public static final String INVENTORYENTRIESOUT_BATCHALLOCATIONS_LIST_COUNT_1 = "count(//ENVELOPE/BODY/DATA/TALLYMESSAGE[";
	public static final String INVENTORYENTRIESOUT_BATCHALLOCATIONS_LIST_COUNT_2 = "]/VOUCHER//INVENTORYENTRIESOUT.LIST[";

	//xpath with place holders
	public static final String VCHTYPE_XPATH = "//ENVELOPE/BODY/DATA/TALLYMESSAGE[{0}]/VOUCHER//@VCHTYPE";
	public static final String ACTION_XPATH = "//ENVELOPE/BODY/DATA/TALLYMESSAGE[{0}]/VOUCHER//@ACTION";
	public static final String DATE_XPATH = "//ENVELOPE/BODY/DATA/TALLYMESSAGE[{0}]/VOUCHER//DATE";
	public static final String VOUCHERTYPENAME_XPATH = "//ENVELOPE/BODY/DATA/TALLYMESSAGE[{0}]/VOUCHER//VOUCHERTYPENAME";
	public static final String VOUCHERNUMBER_XPATH = "//ENVELOPE/BODY/DATA/TALLYMESSAGE[{0}]/VOUCHER//VOUCHERNUMBER";
	public static final String PARTYLEDGERNAME_XPATH = "//ENVELOPE/BODY/DATA/TALLYMESSAGE[{0}]/VOUCHER//PARTYLEDGERNAME";
	public static final String VOUCHERKEY_XPATH = "//ENVELOPE/BODY/DATA/TALLYMESSAGE[{0}]/VOUCHER//VOUCHERKEY";
	public static final String EFFECTIVEDATE_XPATH = "//ENVELOPE/BODY/DATA/TALLYMESSAGE[{0}]/VOUCHER//EFFECTIVEDATE";
	public static final String PERSISTEDVIEW_XPATH = "//ENVELOPE/BODY/DATA/TALLYMESSAGE[{0}]/VOUCHER//PERSISTEDVIEW";
	public static final String ALTERID_XPATH = "//ENVELOPE/BODY/DATA/TALLYMESSAGE[{0}]/VOUCHER//ALTERID";
	public static final String MASTERID_XPATH = "//ENVELOPE/BODY/DATA/TALLYMESSAGE[{0}]/VOUCHER//MASTERID";
	
	public static final String VOUCHER_INVENTORYENTRIESIN_LIST_COUNT = "count(//ENVELOPE/BODY/DATA/TALLYMESSAGE[{0}]/VOUCHER//INVENTORYENTRIESIN.LIST)";
	
	public static final String STOCKITEMNAME_XPATH = "//ENVELOPE/BODY/DATA/TALLYMESSAGE[{0}]/VOUCHER//INVENTORYENTRIESIN.LIST[{1}]/STOCKITEMNAME";
	public static final String RATE_XPATH = "//ENVELOPE/BODY/DATA/TALLYMESSAGE[{0}]/VOUCHER//INVENTORYENTRIESIN.LIST[{1}]/RATE";
	public static final String AMOUNT_XPATH = "//ENVELOPE/BODY/DATA/TALLYMESSAGE[{0}]/VOUCHER//INVENTORYENTRIESIN.LIST[{1}]/AMOUNT";
	public static final String BILLEDQTY_XPATH = "//ENVELOPE/BODY/DATA/TALLYMESSAGE[{0}]/VOUCHER//INVENTORYENTRIESIN.LIST[{1}]/BILLEDQTY";
	
	public static final String INVENTORYENTRIESIN_BATCHALLOCATIONS_LIST_COUNT = "count(//ENVELOPE/BODY/DATA/TALLYMESSAGE[{0}]/VOUCHER//INVENTORYENTRIESIN.LIST[{1}]/BATCHALLOCATIONS.LIST)";
	
	public static final String UDF_671089649_XPATH = "//ENVELOPE/BODY/DATA/TALLYMESSAGE[{0}]/VOUCHER//INVENTORYENTRIESIN.LIST[{1}]/BATCHALLOCATIONS.LIST[{2}]/UDF_UDF_671089649.LIST//UDF_UDF_671089649";
	public static final String UDF_671089650_XPATH = "//ENVELOPE/BODY/DATA/TALLYMESSAGE[{0}]/VOUCHER//INVENTORYENTRIESIN.LIST[{1}]/BATCHALLOCATIONS.LIST[{2}]/UDF_UDF_671089650.LIST//UDF_UDF_671089650";
	public static final String UDF_671089651_XPATH = "//ENVELOPE/BODY/DATA/TALLYMESSAGE[{0}]/VOUCHER//INVENTORYENTRIESIN.LIST[{1}]/BATCHALLOCATIONS.LIST[{2}]/UDF_UDF_671089651.LIST//UDF_UDF_671089651";
	public static final String UDF_671089652_XPATH = "//ENVELOPE/BODY/DATA/TALLYMESSAGE[{0}]/VOUCHER//INVENTORYENTRIESIN.LIST[{1}]/BATCHALLOCATIONS.LIST[{2}]/UDF_UDF_671089652.LIST//UDF_UDF_671089652";
	public static final String UDF_671089655_XPATH = "//ENVELOPE/BODY/DATA/TALLYMESSAGE[{0}]/VOUCHER//INVENTORYENTRIESIN.LIST[{1}]/BATCHALLOCATIONS.LIST[{2}]/UDF_UDF_671089655.LIST//UDF_UDF_671089655";
	public static final String UDF_671089656_XPATH = "//ENVELOPE/BODY/DATA/TALLYMESSAGE[{0}]/VOUCHER//INVENTORYENTRIESIN.LIST[{1}]/BATCHALLOCATIONS.LIST[{2}]/UDF_UDF_671089656.LIST//UDF_UDF_671089656";
	public static final String UDF_671089657_XPATH = "//ENVELOPE/BODY/DATA/TALLYMESSAGE[{0}]/VOUCHER//INVENTORYENTRIESIN.LIST[{1}]/BATCHALLOCATIONS.LIST[{2}]/UDF_UDF_671089657.LIST//UDF_UDF_671089657";
	public static final String UDF_671089660_XPATH = "//ENVELOPE/BODY/DATA/TALLYMESSAGE[{0}]/VOUCHER//INVENTORYENTRIESIN.LIST[{1}]/BATCHALLOCATIONS.LIST[{2}]/UDF_UDF_671089660.LIST//UDF_UDF_671089660";
	public static final String UDF_788530753_XPATH = "//ENVELOPE/BODY/DATA/TALLYMESSAGE[{0}]/VOUCHER//INVENTORYENTRIESIN.LIST[{1}]/BATCHALLOCATIONS.LIST[{2}]/UDF_UDF_788530753.LIST//UDF_UDF_788530753";
	public static final String UDF_788538154_XPATH = "//ENVELOPE/BODY/DATA/TALLYMESSAGE[{0}]/VOUCHER//INVENTORYENTRIESIN.LIST[{1}]/BATCHALLOCATIONS.LIST[{2}]/UDF_UDF_788538154.LIST//UDF_UDF_788538154";
	public static final String UDF_788538155_XPATH = "//ENVELOPE/BODY/DATA/TALLYMESSAGE[{0}]/VOUCHER//INVENTORYENTRIESIN.LIST[{1}]/BATCHALLOCATIONS.LIST[{2}]/UDF_UDF_788538155.LIST//UDF_UDF_788538155";
	public static final String UDF_788538156_XPATH = "//ENVELOPE/BODY/DATA/TALLYMESSAGE[{0}]/VOUCHER//INVENTORYENTRIESIN.LIST[{1}]/BATCHALLOCATIONS.LIST[{2}]/UDF_UDF_788538156.LIST//UDF_UDF_788538156";
	public static final String UDF_788538157_XPATH = "//ENVELOPE/BODY/DATA/TALLYMESSAGE[{0}]/VOUCHER//INVENTORYENTRIESIN.LIST[{1}]/BATCHALLOCATIONS.LIST[{2}]/UDF_UDF_788538157.LIST//UDF_UDF_788538157";
	public static final String UDF_788538159_XPATH = "//ENVELOPE/BODY/DATA/TALLYMESSAGE[{0}]/VOUCHER//INVENTORYENTRIESIN.LIST[{1}]/BATCHALLOCATIONS.LIST[{2}]/UDF_UDF_788538159.LIST//UDF_UDF_788538159";
	
	public static final String VOUCHER_INVENTORYENTRIESOUT_LIST_COUNT = "count(//ENVELOPE/BODY/DATA/TALLYMESSAGE[{0}]/VOUCHER//INVENTORYENTRIESOUT.LIST)";
	
	public static final String STOCKITEMNAME_OUT_XPATH = "//ENVELOPE/BODY/DATA/TALLYMESSAGE[{0}]/VOUCHER//INVENTORYENTRIESOUT.LIST[{1}]/STOCKITEMNAME";
	public static final String RATE_OUT_XPATH = "//ENVELOPE/BODY/DATA/TALLYMESSAGE[{0}]/VOUCHER//INVENTORYENTRIESOUT.LIST[{1}]/RATE";
	public static final String AMOUNT_OUT_XPATH = "//ENVELOPE/BODY/DATA/TALLYMESSAGE[{0}]/VOUCHER//INVENTORYENTRIESOUT.LIST[{1}]/AMOUNT";
	public static final String BILLEDQTY_OUT_XPATH = "//ENVELOPE/BODY/DATA/TALLYMESSAGE[{0}]/VOUCHER//INVENTORYENTRIESOUT.LIST[{1}]/BILLEDQTY";
	
	public static final String INVENTORYENTRIESOUT_BATCHALLOCATIONS_LIST_COUNT = "count(//ENVELOPE/BODY/DATA/TALLYMESSAGE[{0}]/VOUCHER//INVENTORYENTRIESOUT.LIST[{1}]/BATCHALLOCATIONS.LIST)";
	
	public static final String UDF_671089649_OUT_XPATH = "//ENVELOPE/BODY/DATA/TALLYMESSAGE[{0}]/VOUCHER//INVENTORYENTRIESOUT.LIST[{1}]/BATCHALLOCATIONS.LIST[{2}]/UDF_UDF_671089649.LIST//UDF_UDF_671089649";
	public static final String UDF_671089650_OUT_XPATH = "//ENVELOPE/BODY/DATA/TALLYMESSAGE[{0}]/VOUCHER//INVENTORYENTRIESOUT.LIST[{1}]/BATCHALLOCATIONS.LIST[{2}]/UDF_UDF_671089650.LIST//UDF_UDF_671089650";
	public static final String UDF_671089651_OUT_XPATH = "//ENVELOPE/BODY/DATA/TALLYMESSAGE[{0}]/VOUCHER//INVENTORYENTRIESOUT.LIST[{1}]/BATCHALLOCATIONS.LIST[{2}]/UDF_UDF_671089651.LIST//UDF_UDF_671089651";
	public static final String UDF_671089652_OUT_XPATH = "//ENVELOPE/BODY/DATA/TALLYMESSAGE[{0}]/VOUCHER//INVENTORYENTRIESOUT.LIST[{1}]/BATCHALLOCATIONS.LIST[{2}]/UDF_UDF_671089652.LIST//UDF_UDF_671089652";
	public static final String UDF_671089655_OUT_XPATH = "//ENVELOPE/BODY/DATA/TALLYMESSAGE[{0}]/VOUCHER//INVENTORYENTRIESOUT.LIST[{1}]/BATCHALLOCATIONS.LIST[{2}]/UDF_UDF_671089655.LIST//UDF_UDF_671089655";
	public static final String UDF_671089656_OUT_XPATH = "//ENVELOPE/BODY/DATA/TALLYMESSAGE[{0}]/VOUCHER//INVENTORYENTRIESOUT.LIST[{1}]/BATCHALLOCATIONS.LIST[{2}]/UDF_UDF_671089656.LIST//UDF_UDF_671089656";
	public static final String UDF_671089657_OUT_XPATH = "//ENVELOPE/BODY/DATA/TALLYMESSAGE[{0}]/VOUCHER//INVENTORYENTRIESOUT.LIST[{1}]/BATCHALLOCATIONS.LIST[{2}]/UDF_UDF_671089657.LIST//UDF_UDF_671089657";
	public static final String UDF_671089660_OUT_XPATH = "//ENVELOPE/BODY/DATA/TALLYMESSAGE[{0}]/VOUCHER//INVENTORYENTRIESOUT.LIST[{1}]/BATCHALLOCATIONS.LIST[{2}]/UDF_UDF_671089660.LIST//UDF_UDF_671089660";
	public static final String UDF_788530753_OUT_XPATH = "//ENVELOPE/BODY/DATA/TALLYMESSAGE[{0}]/VOUCHER//INVENTORYENTRIESOUT.LIST[{1}]/BATCHALLOCATIONS.LIST[{2}]/UDF_UDF_788530753.LIST//UDF_UDF_788530753";
	public static final String UDF_788538154_OUT_XPATH = "//ENVELOPE/BODY/DATA/TALLYMESSAGE[{0}]/VOUCHER//INVENTORYENTRIESOUT.LIST[{1}]/BATCHALLOCATIONS.LIST[{2}]/UDF_UDF_788538154.LIST//UDF_UDF_788538154";
	public static final String UDF_788538155_OUT_XPATH = "//ENVELOPE/BODY/DATA/TALLYMESSAGE[{0}]/VOUCHER//INVENTORYENTRIESOUT.LIST[{1}]/BATCHALLOCATIONS.LIST[{2}]/UDF_UDF_788538155.LIST//UDF_UDF_788538155";
	public static final String UDF_788538156_OUT_XPATH = "//ENVELOPE/BODY/DATA/TALLYMESSAGE[{0}]/VOUCHER//INVENTORYENTRIESOUT.LIST[{1}]/BATCHALLOCATIONS.LIST[{2}]/UDF_UDF_788538156.LIST//UDF_UDF_788538156";
	public static final String UDF_788538157_OUT_XPATH = "//ENVELOPE/BODY/DATA/TALLYMESSAGE[{0}]/VOUCHER//INVENTORYENTRIESOUT.LIST[{1}]/BATCHALLOCATIONS.LIST[{2}]/UDF_UDF_788538157.LIST//UDF_UDF_788538157";
	public static final String UDF_788538159_OUT_XPATH = "//ENVELOPE/BODY/DATA/TALLYMESSAGE[{0}]/VOUCHER//INVENTORYENTRIESOUT.LIST[{1}]/BATCHALLOCATIONS.LIST[{2}]/UDF_UDF_788538159.LIST//UDF_UDF_788538159";
	
	public static final String VOUCHER_INVENTORYENTRIESIN_STATUS = "IN";
	public static final String VOUCHER_INVENTORYENTRIESOUT_STATUS = "OUT";
	
	public static final String DATE_FORMAT_1 = "yyyyMMddhhmmss";
	
	public static final String TALLY_STOCK = "TALLY_STOCK";
	public static final String TALLY_DAY_BOOK = "TALLY_DAY_BOOK";
	public static final String PRODUCTION_SUMMARY = "PRODUCTION_SUMMARY";
	public static final String SALES_SUMMARY = "SALES_SUMMARY";

	//stock new approach
	public static final String TALLYMESSAGE_COUNT_EXP1 = "count(//ENVELOPE/BODY/DATA/COLLECTION/VOUCHER)";
	public static final String VCHTYPE_XPATH1 = "//ENVELOPE/BODY/DATA/COLLECTION/VOUCHER[{0}]//@VCHTYPE";
	public static final String ACTION_XPATH1 = "//ENVELOPE/BODY/DATA/COLLECTION/VOUCHER[{0}]//@ACTION";
	public static final String DATE_XPATH1 = "//ENVELOPE/BODY/DATA/COLLECTION/VOUCHER[{0}]//DATE";
	public static final String VOUCHERTYPENAME_XPATH1 = "//ENVELOPE/BODY/DATA/COLLECTION/VOUCHER[{0}]//VOUCHERTYPENAME";
	public static final String VOUCHERNUMBER_XPATH1 = "//ENVELOPE/BODY/DATA/COLLECTION/VOUCHER[{0}]//VOUCHERNUMBER";
	public static final String PARTYLEDGERNAME_XPATH1 = "//ENVELOPE/BODY/DATA/COLLECTION/VOUCHER[{0}]//PARTYLEDGERNAME";
	public static final String VOUCHERKEY_XPATH1 = "//ENVELOPE/BODY/DATA/COLLECTION/VOUCHER[{0}]//VOUCHERKEY";
	public static final String EFFECTIVEDATE_XPATH1 = "//ENVELOPE/BODY/DATA/COLLECTION/VOUCHER[{0}]//EFFECTIVEDATE";
	public static final String PERSISTEDVIEW_XPATH1 = "//ENVELOPE/BODY/DATA/COLLECTION/VOUCHER[{0}]//PERSISTEDVIEW";
	public static final String ALTERID_XPATH1 = "//ENVELOPE/BODY/DATA/COLLECTION/VOUCHER[{0}]//ALTERID";
	public static final String MASTERID_XPATH1 = "//ENVELOPE/BODY/DATA/COLLECTION/VOUCHER[{0}]//MASTERID";
	
	public static final String VOUCHER_INVENTORYENTRIESIN_LIST_COUNT1 = "count(//ENVELOPE/BODY/DATA/COLLECTION/VOUCHER[{0}]//INVENTORYENTRIESIN.LIST)";
	public static final String VOUCHER_INVENTORYENTRIESOUT_LIST_COUNT1 = "count(//ENVELOPE/BODY/DATA/COLLECTION/VOUCHER[{0}]//INVENTORYENTRIESOUT.LIST)";
	
	public static final String STOCKITEMNAME_XPATH1 = "//ENVELOPE/BODY/DATA/COLLECTION/VOUCHER[{0}]//INVENTORYENTRIESIN.LIST[{1}]/STOCKITEMNAME";
	public static final String RATE_XPATH1 = "//ENVELOPE/BODY/DATA/COLLECTION/VOUCHER[{0}]//INVENTORYENTRIESIN.LIST[{1}]/RATE";
	public static final String AMOUNT_XPATH1 = "//ENVELOPE/BODY/DATA/COLLECTION/VOUCHER[{0}]//INVENTORYENTRIESIN.LIST[{1}]/AMOUNT";
	public static final String BILLEDQTY_XPATH1 = "//ENVELOPE/BODY/DATA/COLLECTION/VOUCHER[{0}]//INVENTORYENTRIESIN.LIST[{1}]/BILLEDQTY";
	
	public static final String INVENTORYENTRIESIN_BATCHALLOCATIONS_LIST_COUNT1 = "count(//ENVELOPE/BODY/DATA/COLLECTION/VOUCHER[{0}]//INVENTORYENTRIESIN.LIST[{1}]/BATCHALLOCATIONS.LIST)";
	
	public static final String UDF_671089649_XPATH1 = "//ENVELOPE/BODY/DATA/COLLECTION/VOUCHER[{0}]//INVENTORYENTRIESIN.LIST[{1}]/BATCHALLOCATIONS.LIST[{2}]/UDF_UDF_671089649.LIST//UDF_UDF_671089649";
	public static final String UDF_671089650_XPATH1 = "//ENVELOPE/BODY/DATA/COLLECTION/VOUCHER[{0}]//INVENTORYENTRIESIN.LIST[{1}]/BATCHALLOCATIONS.LIST[{2}]/UDF_UDF_671089650.LIST//UDF_UDF_671089650";
	public static final String UDF_671089651_XPATH1 = "//ENVELOPE/BODY/DATA/COLLECTION/VOUCHER[{0}]//INVENTORYENTRIESIN.LIST[{1}]/BATCHALLOCATIONS.LIST[{2}]/UDF_UDF_671089651.LIST//UDF_UDF_671089651";
	public static final String UDF_671089652_XPATH1 = "//ENVELOPE/BODY/DATA/COLLECTION/VOUCHER[{0}]//INVENTORYENTRIESIN.LIST[{1}]/BATCHALLOCATIONS.LIST[{2}]/UDF_UDF_671089652.LIST//UDF_UDF_671089652";
	public static final String UDF_671089655_XPATH1 = "//ENVELOPE/BODY/DATA/COLLECTION/VOUCHER[{0}]//INVENTORYENTRIESIN.LIST[{1}]/BATCHALLOCATIONS.LIST[{2}]/UDF_UDF_671089655.LIST//UDF_UDF_671089655";
	public static final String UDF_671089656_XPATH1 = "//ENVELOPE/BODY/DATA/COLLECTION/VOUCHER[{0}]//INVENTORYENTRIESIN.LIST[{1}]/BATCHALLOCATIONS.LIST[{2}]/UDF_UDF_671089656.LIST//UDF_UDF_671089656";
	public static final String UDF_671089657_XPATH1 = "//ENVELOPE/BODY/DATA/COLLECTION/VOUCHER[{0}]//INVENTORYENTRIESIN.LIST[{1}]/BATCHALLOCATIONS.LIST[{2}]/UDF_UDF_671089657.LIST//UDF_UDF_671089657";
	public static final String UDF_671089660_XPATH1 = "//ENVELOPE/BODY/DATA/COLLECTION/VOUCHER[{0}]//INVENTORYENTRIESIN.LIST[{1}]/BATCHALLOCATIONS.LIST[{2}]/UDF_UDF_671089660.LIST//UDF_UDF_671089660";
	public static final String UDF_788530753_XPATH1 = "//ENVELOPE/BODY/DATA/COLLECTION/VOUCHER[{0}]//INVENTORYENTRIESIN.LIST[{1}]/BATCHALLOCATIONS.LIST[{2}]/UDF_UDF_788530753.LIST//UDF_UDF_788530753";
	public static final String UDF_788538154_XPATH1 = "//ENVELOPE/BODY/DATA/COLLECTION/VOUCHER[{0}]//INVENTORYENTRIESIN.LIST[{1}]/BATCHALLOCATIONS.LIST[{2}]/UDF_UDF_788538154.LIST//UDF_UDF_788538154";
	public static final String UDF_788538155_XPATH1 = "//ENVELOPE/BODY/DATA/COLLECTION/VOUCHER[{0}]//INVENTORYENTRIESIN.LIST[{1}]/BATCHALLOCATIONS.LIST[{2}]/UDF_UDF_788538155.LIST//UDF_UDF_788538155";
	public static final String UDF_788538156_XPATH1 = "//ENVELOPE/BODY/DATA/COLLECTION/VOUCHER[{0}]//INVENTORYENTRIESIN.LIST[{1}]/BATCHALLOCATIONS.LIST[{2}]/UDF_UDF_788538156.LIST//UDF_UDF_788538156";
	public static final String UDF_788538157_XPATH1 = "//ENVELOPE/BODY/DATA/COLLECTION/VOUCHER[{0}]//INVENTORYENTRIESIN.LIST[{1}]/BATCHALLOCATIONS.LIST[{2}]/UDF_UDF_788538157.LIST//UDF_UDF_788538157";
	public static final String UDF_788538159_XPATH1 = "//ENVELOPE/BODY/DATA/COLLECTION/VOUCHER[{0}]//INVENTORYENTRIESIN.LIST[{1}]/BATCHALLOCATIONS.LIST[{2}]/UDF_UDF_788538159.LIST//UDF_UDF_788538159";

	public static final String BATCH_ALLOCATION_BATCH_NAME = "//ENVELOPE/BODY/DATA/COLLECTION/VOUCHER[{0}]//INVENTORYENTRIESIN.LIST[{1}]/BATCHALLOCATIONS.LIST[{2}]/BATCHNAME";
	public static final String BATCH_ALLOCATION_AMOUNT = "//ENVELOPE/BODY/DATA/COLLECTION/VOUCHER[{0}]//INVENTORYENTRIESIN.LIST[{1}]/BATCHALLOCATIONS.LIST[{2}]/AMOUNT";
	
	public static final String BATCH_ALLOCATION_BILLED_QTY = "//ENVELOPE/BODY/DATA/COLLECTION/VOUCHER[{0}]//INVENTORYENTRIESIN.LIST[{1}]/BATCHALLOCATIONS.LIST[{2}]/BILLEDQTY";
	
	//production and sales summary
	public static final String ENVELOPE_DSPSTKINFO_COUNT = "count(//ENVELOPE/DSPSTKINFO)";
	public static final String ENVELOPE_DSPSTKINFO_DSPSTKIN_DSPINQTY = "//ENVELOPE/DSPSTKINFO[{0}]//DSPSTKIN/DSPINQTY";
	
	public static final String ENVELOPE_DSPACCINFO_COUNT = "count(//ENVELOPE/DSPACCINFO)";
	public static final String ENVELOPE_DSPACCINFO_DSPCRAMT_DSPDRAMTA = "//ENVELOPE/DSPACCINFO[{0}]//DSPCRAMT/DSPCRAMTA";
	
	
	public static final String DB_HISTORY_DATA_ADD = "insert into HISTORY_DATA(GROUP_NAME, AMOUNT, FREQUENCY, MONTH, YEAR, STATUS, LAST_UPDATED, COMPANY_ID) values (?, ?, ?, ?, ?, ?, ?, ?)";
	public static final String DB_HISTORY_DATA_DELETE = "DELETE FROM HISTORY_DATA WHERE YEAR = ? AND GROUP_NAME = ? AND FREQUENCY = ?";
	//public static final String DB_HISTORY_DATA_DELETE = "DELETE FROM HISTORY_DATA WHERE YEAR = ?";
}
